[package]
name = "bcsv_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.11.2"
clap = { version = "4.3.2", features = ["derive"] }
