[package]
name = "bcsv_tool"
version = "2.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
libbcsv = { version = "0.4.0", path = "libbcsv" }
