name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - uses: actions/upload-artifact@v3.1.2
      if: runner.os == 'Windows'
      with:
        name: ${{matrix.os}}
        path: target/release/bcsv_tool.exe
    - uses: actions/upload-artifact@v3.1.2
      if: runner.os != 'Windows'
      with:
        name: ${{matrix.os}}
        path: target/release/bcsv_tool
