name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: cargo build --release --verbose
    - uses: actions/upload-artifact@v4.6.0
      if: runner.os == 'Windows'
      with:
        name: ${{matrix.os}}
        path: target/release/bcsv_tool.exe
    - uses: actions/upload-artifact@v4.6.0
      if: runner.os != 'Windows'
      with:
        name: ${{matrix.os}}
        path: target/release/bcsv_tool
  build-serde:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recusive
    - name: Build
      run: cargo build --release --features serde --verbose
    - uses: actions/upload-artifact@v4.6.0
      if: runner.os == 'Windows'
      with:
        name: ${{ matrix.os }}-serde
        path: target/release/bcsv_tool.exe
    - uses: actions/upload-artifact@v4.6.0
      if: runner.os != 'Windows'
      with:
        name: ${{ matrix.os }}-serde
        path: target/release/bcsv_tool
  publish:
    needs: [build, build-serde]
    if: github.event_name == 'push'
    runs-on: windows-latest
      
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v4.1.8
      with:
        name: windows-latest
        path: ${{github.workspace}}/windows
    - uses: actions/download-artifact@v4.1.8
      with:
        name: ubuntu-latest
        path: ${{github.workspace}}/linux
    - uses: actions/download-artifact@v4.1.8
      with:
        name: macos-latest
        path: ${{github.workspace}}/macos
    - uses: actions/download-artifact@v4.1.8
      with:
        name: windows-latest-serde
        path: ${{github.workspace}}/windows-serde
    - uses: actions/download-artifact@v4.1.8
      with:
        name: ubuntu-latest-serde
        path: ${{github.workspace}}/ubuntu-serde
    - uses: actions/download-artifact@v4.1.8
      with:
        name: macos-latest-serde
        path: ${{github.workspace}}/macos-serde
    - run: 7z a bcsv_tool.zip windows linux macos windows-serde linux-serde macos-serde lookup_supermariogalaxy.txt
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Auto"
        prerelease: true
        title: "Auto Build"
        files: |
            *.zip
